apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prepforall

resources:
  - namespace.yaml
  - rbac.yaml
  - api/
  - judge/
  - ingress/
  - observability/

commonLabels:
  app.kubernetes.io/part-of: prepforall
