apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secrets.yaml

patches:
  - path: api-patch.yaml
    target:
      kind: Deployment
      name: api
  - path: judge-patch.yaml
    target:
      kind: Deployment
      name: judge

# Override configmap for dev environment
configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - ENV=development
      - ALLOWED_ORIGINS=["http://localhost:3000","http://localhost:5173"]
