apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: prepforall
data:
  ENV: "production"
  PORT: "8080"
  JWT_EXPIRY: "24h"
  ALLOWED_ORIGINS: '["https://prepforall.com","https://app.prepforall.com"]'
